feat: add TextProcessor
makarkananov/yadro-microservices pull request #2
Opened 2024-03-27 15:47 UTC by makarkananov

2024-03-28 08:19 UTC, vbelogrudov requested changes
интересное решение, в идеале бы иметь одну точку входа для нормализации входного текста, чтобы не думать, какую фазу вызывать. То есть как пользователь я хочу
tp := NewProcessor(stopwords)
keywords, err := tp.Process(phrase)

2024-03-28 08:19 UTC, vbelogrudov commented on Makefile
> +run: build
не очень понятно, зачем run

2024-03-28 08:19 UTC, vbelogrudov commented on cmd/cli/main.go
> +	tp := processing.NewTextProcessor(*text, *language)
неплохо разбито по стадиям, 
может разбить их по другому, чтобы можно было несколько раз вызывать этот процессор. То есть 
tp := processing.NewTextProcessor(stopwordsfile, language)
res, err := tp.RemoveStopWords(),
res, err := tp.Normalize(res),
...

2024-03-28 08:19 UTC, vbelogrudov commented on cmd/cli/main.go
> +	tp := processing.NewTextProcessor(*text, *language)
иначе для каждого комикса в будущем нам надо создавать процессор, который в свою очередь будет каждый раз зачитывать стоп слова

2024-03-28 08:19 UTC, vbelogrudov commented on processing/processing.go
> +	words := strings.Fields(text)
можно попробовать функцию strings.FieldsFunc, которая разобьет не только по пробелам, но и по пунктуации

2024-03-28 08:19 UTC, vbelogrudov commented on processing/processing.go
> +	return strings.Join(tp.tokens, " ")
в идеале нам лучше слайс, а уже fmt.Print* сам соединит, если нужно. Иначе нам опять сплиттить в следующих заданиях

2024-03-28 08:19 UTC, vbelogrudov commented on processing/processing.go
> +	var normalizedWords []string
здесь можно сразу нужного размера слайс, через make

2024-03-28 08:23 UTC, vbelogrudov commented
➜  yadro-microservices git:(task-1) ✗ ./myapp -s 'going east-west!'
go east-west

Можно еще делить по дефису

2024-03-29 14:22 UTC, vbelogrudov commented
Все работает  как надо, есть последнее замечание -
желательно делать LoadStopWordsFromFile один раз, например, при создании TextProcessor. Иначе мы каждый раз загружаем его в следующем случае
	if tp.stopWordsFile != "" {
		stopwords.LoadStopWordsFromFile(tp.stopWordsFile, tp.lang, " ")
	}

2024-03-29 18:09 UTC, makarkananov commented
Спасибо за ревью, кажется, все пофиксил) Могу закрывать issue? 😸

2024-03-30 15:09 UTC, vbelogrudov approved these changes
можно мержить!

2024-03-30 15:10 UTC, merged