feat: task-3 without *
makarkananov/yadro-microservices pull request #6
Opened 2024-04-10 21:54 UTC by makarkananov

2024-04-10 22:09 UTC, makarkananov commented
Кажется, большая часть критериев приемки уже была выполнена в прошлом задании 😸 
Немного подправил код для соответствия пунктам 1-5. Шестой пункт пока выполнить не успел.

Заранее спасибо за ревью! ❤️

2024-04-11 10:42 UTC, vbelogrudov commented
type ComicDatabase interface {
	Save(data interface{}) error
	Load(v interface{}) error
}

мелочь - у interface{} в свежих релизах Го появился alias - "any"

2024-04-11 10:50 UTC, vbelogrudov commented
```
	// Merge new comics with existing ones
	for id, comic := range existingComics {
		if _, ok := comicsMap[id]; !ok {
			comicsMap[id] = comic
		}
	}
```
у нас не может быть в comicsMap записей из existingComics.
Также можно чуть проще скопировать один map в другой - https://pkg.go.dev/golang.org/x/exp/maps#Copy

2024-04-11 11:14 UTC, vbelogrudov commented
все получилось компактно, отрабытывает быстро и прерывается правильно. Маленькая проблема - 
➜  yadro-microservices git:(main) ✗ cat database.json| jq 'keys' | wc -l
2905
это я с прерываниями в несколько раз грузил.
➜  yadro-microservices git:(main) ✗ cat database.json| jq 'keys' | wc -l     
2919
это без прерываний, без 404го должно быть 2917

2024-04-11 11:14 UTC, vbelogrudov requested changes

2024-04-11 11:14 UTC, vbelogrudov commented on internal/service/xkcdservice.go
> +		existingIDs[i+1] = true
почему  i+1? у нас i - ID комикса

2024-04-16 06:46 UTC, vbelogrudov approved these changes

2024-04-24 09:53 UTC, merged